"""empty message

Revision ID: d1e6c60de9da
Revises: fe1122acba09
Create Date: 2020-01-13 20:10:55.505710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e6c60de9da'
down_revision = 'fe1122acba09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_reset_password_token', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_reset_password_token')
    # ### end Alembic commands ###
