import sys
import os
import zipfile
import base64
from io import BytesIO

def main():
    if len(sys.argv>1):
        projectname = sys.argv[1]
    else:
        projectname = input("Enter Project Name")
    make_project(projectname)
    
def make_project(projectname):
    if not os.path.exists(projectname):
        os.makedirs(projectname)
    else:
        i = input(projectname+" Already Exists!! Do You Want to Overwrite?[Y/n]")
        if i not  in ['y','Y','Yes','YES']:
            return None
    shutil.rmtree(projectname)           
    os.makedirs(projectname)
    os.chdir(projectname)
    
    content1 = '''UEsDBBQAAAAIAAGkI1D6kcQMQAAAAFMAAAAJAAAAY29uZmlnLnB5S87PS8tMV7BVqFbg5VJ383EM9o539QtTt1J3cQ1z9fEP8HX1C1HXgcs5BgQA5YoTkYRcXJ1C3YGChiCxWl4uAFBLAwQUAAAACAABpCNQ0ih/V90AAACgAQAACQAAAG1hbmFnZS5weWVQQYrDMAy8G/wH3ZxAmwcsBPYNe12KcV27MYktIyeF/n7t2E0pq4uk0TAayfmItAImzlqZtmsk1Ca9Ib04PXNmCT1oDNbd4TXZO85uxoILbu36L84gh0WC2Twz2DgNL4FpMOHhCMNvplxgbJS946yqSUlbSIYehg7Rt7UhDzsS8blOGODswS4qzZBR0RdmUeHsezc+3Am32PVVN0OHXlTlyFJV7qDRexVunTh2i9NkljiKnwzAOpm2qA2b5n+n9Re1/rikGsufLRcG5Y2UMI4gpPTKBSlFE9ht5vwHUEsBAh8AFAAAAAgAAaQjUPqRxAxAAAAAUwAAAAkAJAAAAAAAAAAgAAAAAAAAAGNvbmZpZy5weQoAIAAAAAAAAQAYABZ1aMFGwtUBFnVowUbC1QEWdWjBRsLVAVBLAQIfABQAAAAIAAGkI1DSKH9X3QAAAKABAAAJACQAAAAAAAAAIAAAAGcAAABtYW5hZ2UucHkKACAAAAAAAAEAGAAWdWjBRsLVARZ1aMFGwtUBFnVowUbC1QFQSwUGAAAAAAIAAgC2AAAAawEAAAAA'''
    content2 = '''UEsDBBQAAAAIAAGkI1DztdFlTwAAAF8AAAAIAAAAdmlld3MucHldykEKgCAQRuG94B1mp246QJcRwd+SHJVpgo6f697ug1dkMJWW7osqzyFKgp4hUcGzJYU11mQUOgcjznTAh90aWgn0kf7/vavL73YqNxc+UEsDBAoAAAAAAAGkI1AAAAAAAAAAAAAAAAAKAAAAdGVtcGxhdGVzL1BLAwQUAAAACAABpCNQ2DhioUAAAABXAAAAFAAAAHRlbXBsYXRlcy9pbmRleC5odG1ss8koyc2x4+WyKcksyUkFMjxSc3LygXx9mIBNUn5KJYjOMLQLT81Jzs9NVQjJV3DLSSzOttEHCoIUw9ToQ40DAFBLAwQUAAAACAABpCNQ7ZHTyB8AAAApAAAACwAAAF9faW5pdF9fLnB5SyvKz1XQSywoUMjMLcgvKlEAMnm5IKIwodKinGIFAFBLAwQUAAAACAABpCNQBSfM1z0AAABHAAAABgAAAGFwcC5weePlUlZwVHBKLM5MVnDLSSzOVnAsKODlSivKz1VIA/Mzcwvyi0ogkrxciQUFCrYQjkZ8fF5ibmp8vCYvFwBQSwMEFAAAAAgAAaQjUKnZRrBfAAAAhwAAAAcAAAB1cmxzLnB5SyvKz1XQSywoUMjMLcgvKlEAMROLQRQvF0SyLDO1vBgmnZGfmxpfkJieysvFy1ValKNgC1Kql5iSEg/kxReV5sBkChJLMoCy0WCOhrq+uo46SLO6DtwITR2Q0lgQAQBQSwECHwAUAAAACAABpCNQ87XRZU8AAABfAAAACAAkAAAAAAAAACAAAAAAAAAAdmlld3MucHkKACAAAAAAAAEAGAAWdWjBRsLVARZ1aMFGwtUBFnVowUbC1QFQSwECHwAKAAAAAAABpCNQAAAAAAAAAAAAAAAACgAkAAAAAAAAABAAAAB1AAAAdGVtcGxhdGVzLwoAIAAAAAAAAQAYABZ1aMFGwtUBbw/wxEbC1QEWdWjBRsLVAVBLAQIfABQAAAAIAAGkI1DYOGKhQAAAAFcAAAAUACQAAAAAAAAAIAAAAJ0AAAB0ZW1wbGF0ZXMvaW5kZXguaHRtbAoAIAAAAAAAAQAYABZ1aMFGwtUBFnVowUbC1QEWdWjBRsLVAVBLAQIfABQAAAAIAAGkI1DtkdPIHwAAACkAAAALACQAAAAAAAAAIAAAAA8BAABfX2luaXRfXy5weQoAIAAAAAAAAQAYABZ1aMFGwtUBFnVowUbC1QEWdWjBRsLVAVBLAQIfABQAAAAIAAGkI1AFJ8zXPQAAAEcAAAAGACQAAAAAAAAAIAAAAFcBAABhcHAucHkKACAAAAAAAAEAGAAWdWjBRsLVARZ1aMFGwtUBFnVowUbC1QFQSwECHwAUAAAACAABpCNQqdlGsF8AAACHAAAABwAkAAAAAAAAACAAAAC4AQAAdXJscy5weQoAIAAAAAAAAQAYABZ1aMFGwtUBFnVowUbC1QEWdWjBRsLVAVBLBQYAAAAABgAGACoCAAA8AgAAAAA='''
    
    bootstrap(content1)
    open('config.py','w').write('''config = { 
'FLASK_ENV':'DEVELOPMENT',
'FLASK_APP':'sa',
'FLASK_DEBUG':'1',
}
'''
    os.makedirs(projectname)
    bootstrap(content2)
    
def bootstrap(cnt):
    decoded = base64.b64decode(cnt)
    file = BytesIO(decoded)
    zipped = zipfile.ZipFile(file)
    zipped.extractall()
    