# Generated by Django 3.0 on 2019-12-13 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field1', to='core.Field')),
                ('field2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field2', to='core.Field')),
                ('field3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field3', to='core.Field')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
